// app/src/views/DashboardView.tsx
import React, { useState, useMemo } from "react"
import { useQuery, useMutation } from "@apollo/client"
import { gql } from "@apollo/client"
import toast from "react-hot-toast"
import HeaderMenu from "../components/common/HeaderMenu"
import DashboardCard from "../components/whiteboard/DashboardCard"
import CreateWhiteboardModal from "../components/whiteboard/CreateWhiteboardModal"

const GET_WHITEBOARDS = gql`
    query GetWhiteboards {
        getAll {
            id
            name
            description
            elements
            createdAt
            updatedAt
        }
    }
`

const CREATE_WHITEBOARD = gql`
    mutation CreateWhiteboard($input: CreateWhiteboardInput!) {
        create(input: $input) {
            id
            message
        }
    }
`

interface Whiteboard {
    id: string
    name: string
    description: string
    elements: any[]
}

interface WhiteboardPayload {
    name: string
    description: string
}

const DashboardView: React.FC = () => {
    const [searchQuery, setSearchQuery] = useState("")
    const [isAddWhiteboardModalOpen, setIsAddWhiteboardModalOpen] = useState(false)

    const { data, loading, error, refetch } = useQuery(GET_WHITEBOARDS)
    const [createWhiteboard] = useMutation(CREATE_WHITEBOARD)

    const whiteboards = useMemo(() => {
        return data?.getAll || []
    }, [data])

    const filteredBoards = useMemo(() => {
        if (!searchQuery.trim()) {
            return whiteboards
        }

        return whiteboards.filter(
            (board: Whiteboard) =>
                board.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                board.description.toLowerCase().includes(searchQuery.toLowerCase())
        )
    }, [whiteboards, searchQuery])

    const handleClose = () => {
        setIsAddWhiteboardModalOpen(false)
    }

    const handleEditWhiteboardModal = (payload: WhiteboardPayload) => {
        console.log("Edit Whiteboard Modal Opened", payload)
    }

    const handleCreate = async (payload: WhiteboardPayload) => {
        try {
            const result = await createWhiteboard({
                variables: {
                    input: {
                        name: payload.name,
                        description: payload.description,
                    },
                },
            })

            toast.success(result.data?.create?.message || "Whiteboard created successfully")
            await refetch()
        } catch (error) {
            toast.error("Failed to create whiteboard")
        }

        setIsAddWhiteboardModalOpen(false)
    }

    return (
        <>
            <HeaderMenu />

            <div className="flex justify-start items-center my-8 ml-8">
                <input
                    type="text"
                    placeholder="Search..."
                    className="px-3 py-2 border border-gray-300 rounded-md min-w-[240px] focus:outline-none focus:ring-2 focus:ring-blue-200"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                />
                <button
                    onClick={() => setIsAddWhiteboardModalOpen(true)}
                    className="ml-4 px-4 py-2 bg-blue-600 text-white rounded cursor-pointer hover:bg-blue-700 focus:outline-none"
                >
                    Add Whiteboard
                </button>
            </div>

            {loading && (
                <div className="flex justify-center items-center py-8">
                    <div className="text-gray-600">Loading whiteboards...</div>
                </div>
            )}

            {error && (
                <div className="flex justify-center items-center py-8">
                    <div className="text-red-600">Error loading whiteboards. Please try again.</div>
                </div>
            )}

            {!loading && !error && (
                <div className="flex flex-wrap gap-6 justify-center mx-8">
                    {filteredBoards.length === 0 ? (
                        <div className="text-center py-8 text-gray-600">
                            {searchQuery.trim() ? (
                                <div>No whiteboards found matching "{searchQuery}"</div>
                            ) : (
                                <div>No whiteboards available. Create your first whiteboard!</div>
                            )}
                        </div>
                    ) : (
                        filteredBoards.map((card: Whiteboard) => (
                            <div
                                key={card.id}
                                className="bg-white border border-gray-200 rounded-lg w-64 shadow-sm flex flex-col overflow-hidden"
                            >
                                <DashboardCard
                                    id={card.id}
                                    name={card.name}
                                    description={card.description}
                                    onOpenEditWhiteboardModal={handleEditWhiteboardModal}
                                />
                            </div>
                        ))
                    )}
                </div>
            )}

            <CreateWhiteboardModal
                isOpen={isAddWhiteboardModalOpen}
                onClose={handleClose}
                onCreate={handleCreate}
            />
        </>
    )
}

export default DashboardView

// app/src/views/DashboardView.vue
<script lang="ts" setup>
import { ref, computed, onMounted } from "vue"
import { useToast } from "vue-toastification"
import { CREATE_WHITEBOARD, GET_WHITEBOARDS } from "@/api/whiteboard"
import { useMutation, useQuery } from "@vue/apollo-composable"
import { FetchResult } from "@apollo/client/core"
import HeaderMenu from "@/components/common/HeaderMenu.vue"
import DashboardCard from "@/components/whiteboard/DashboardCard.vue"
import CreateWhiteboardModal from "@/components/whiteboard/CreateWhiteboardModal.vue"

type CreateWhiteboardResult = FetchResult<{ create: { message: string } }>
type WhiteboardPayload = {
    name: string
    description: string
}
type Whiteboard = {
    id: string
    name: string
    description: string
    elements: any[]
}

const { mutate } = useMutation(CREATE_WHITEBOARD)
const { result, loading, error, refetch } = useQuery(GET_WHITEBOARDS)
const toast = useToast()
const searchQuery = ref("")
const isAddWhiteboardModalOpen = ref(false)

const whiteboards = computed(() => {
    return result.value?.getAll || []
})

const filteredBoards = computed(() => {
    if (!searchQuery.value.trim()) {
        return whiteboards.value
    }

    return whiteboards.value.filter(
        (board: Whiteboard) =>
            board.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
            board.description.toLowerCase().includes(searchQuery.value.toLowerCase())
    )
})

onMounted(() => {
    !result.value && refetch()
})

function handleClose() {
    isAddWhiteboardModalOpen.value = false
}

function handleEditWhiteboardModal(payload: WhiteboardPayload) {
    console.log("Edit Whiteboard Modal Opened", payload)
}

async function handleCreate(payload: WhiteboardPayload) {
    try {
        const result: CreateWhiteboardResult = await mutate({
            input: {
                name: payload.name,
                description: payload.description,
            },
        })

        toast.success(result.data?.create?.message || "Whiteboard created successfully")
        await refetch()
    } catch (error) {
        toast.error("Failed to create whiteboard")
    }

    isAddWhiteboardModalOpen.value = false
}
</script>

<template>
    <HeaderMenu />

    <div class="flex justify-start items-center my-8 ml-8">
        <input
            type="text"
            placeholder="Search..."
            class="px-3 py-2 border border-gray-300 rounded-md min-w-[240px] focus:outline-none focus:ring-2 focus:ring-blue-200"
            v-model="searchQuery"
        />
        <button
            @click="isAddWhiteboardModalOpen = true"
            class="ml-4 px-4 py-2 bg-blue-600 text-white rounded cursor-pointer hover:bg-blue-700 focus:outline-none"
        >
            Add Whiteboard
        </button>
    </div>

    <div v-if="loading" class="flex justify-center items-center py-8">
        <div class="text-gray-600">Loading whiteboards...</div>
    </div>

    <div v-else-if="error" class="flex justify-center items-center py-8">
        <div class="text-red-600">Error loading whiteboards. Please try again.</div>
    </div>

    <div v-else class="flex flex-wrap gap-6 justify-center mx-8">
        <div v-if="filteredBoards.length === 0" class="text-center py-8 text-gray-600">
            <div v-if="searchQuery.trim()">No whiteboards found matching "{{ searchQuery }}"</div>
            <div v-else>No whiteboards available. Create your first whiteboard!</div>
        </div>

        <div
            v-for="card in filteredBoards"
            :key="card.id"
            class="bg-white border border-gray-200 rounded-lg w-64 shadow-sm flex flex-col overflow-hidden"
        >
            <DashboardCard
                :id="card.id"
                :name="card.name"
                :description="card.description"
                @openEditWhiteboardModal="handleEditWhiteboardModal"
            />
        </div>
    </div>

    <CreateWhiteboardModal
        :isOpen="isAddWhiteboardModalOpen"
        @close="handleClose"
        @create="handleCreate"
    />
</template>
