// app/src/components/common/Modal.tsx
import React from "react"

interface ModalProps {
    isOpen: boolean
    onClose: () => void
    children: React.ReactNode
    title?: string
}

const Modal: React.FC<ModalProps> = ({ isOpen, onClose, children, title }) => {
    if (!isOpen) return null

    return (
        <div 
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
            onClick={onClose}
        >
            <div 
                className="bg-white rounded-lg p-6 max-w-md w-full mx-4"
                onClick={(e) => e.stopPropagation()}
            >
                {title && (
                    <h2 className="text-xl font-semibold mb-4">{title}</h2>
                )}
                {children}
            </div>
        </div>
    )
}

export default Modal

// app/src/components/common/Modal.vue
<script setup>
import { Dialog, DialogPanel } from "@headlessui/vue"
defineProps({
    isOpen: Boolean,
    onClose: Function,
})
</script>

<template>
    <Dialog
        :open="isOpen"
        @close="onClose"
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/40"
    >
        <DialogPanel class="bg-white p-6 rounded-xl shadow-lg w-full max-w-md">
            <slot></slot>
        </DialogPanel>
    </Dialog>
</template>
